# Generated by Django 4.1.1 on 2024-05-01 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Rate Name')),
                ('description', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Rate description')),
                ('days_count', models.SmallIntegerField(blank=True, help_text='If days count = 0, access is indefinite and ends at the end of the last available week', null=True, verbose_name='Days Count')),
            ],
            options={
                'verbose_name': 'Rate',
                'verbose_name_plural': 'Rates',
                'ordering': ['id'],
            },
        ),
    ]
